# Keep it simple: catch bugs and performance issues, skip style nitpicking
AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable
  SuggestExtensions: false

# Lint cops catch actual bugs - keep these on
Lint:
  Enabled: true

# Performance cops catch slow code patterns
Performance:
  Enabled: true

# Disable all style cops - too opinionated
Style:
  Enabled: false

# Disable layout cops - formatting preferences vary
Layout:
  Enabled: false

# Disable metrics cops - arbitrary limits
Metrics:
  Enabled: false

# Disable naming cops - naming is subjective
Naming:
  Enabled: false

# Disable security cops that are too noisy (Lint covers the important ones)
Security:
  Enabled: false
